//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Presentation.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auction.Presentation.Localization.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string _admin_add {
            get {
                return ResourceManager.GetString("_admin_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add auction.
        /// </summary>
        public static string _admin_addAuction {
            get {
                return ResourceManager.GetString("_admin_addAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string _admin_addCategory {
            get {
                return ResourceManager.GetString("_admin_addCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add product.
        /// </summary>
        public static string _admin_addProduct {
            get {
                return ResourceManager.GetString("_admin_addProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add user.
        /// </summary>
        public static string _admin_addUser {
            get {
                return ResourceManager.GetString("_admin_addUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string _admin_auction_TLOCATION {
            get {
                return ResourceManager.GetString("_admin_auction_TLOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction name.
        /// </summary>
        public static string _admin_auction_TNAME {
            get {
                return ResourceManager.GetString("_admin_auction_TNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string _admin_auction_TTYPE {
            get {
                return ResourceManager.GetString("_admin_auction_TTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev. page.
        /// </summary>
        public static string _admin_backPage {
            get {
                return ResourceManager.GetString("_admin_backPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string _admin_category_TDESC {
            get {
                return ResourceManager.GetString("_admin_category_TDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string _admin_category_TNAME {
            get {
                return ResourceManager.GetString("_admin_category_TNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string _admin_edit {
            get {
                return ResourceManager.GetString("_admin_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit auction.
        /// </summary>
        public static string _admin_editAuction {
            get {
                return ResourceManager.GetString("_admin_editAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        public static string _admin_editCategory {
            get {
                return ResourceManager.GetString("_admin_editCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string _admin_editProduct {
            get {
                return ResourceManager.GetString("_admin_editProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit user.
        /// </summary>
        public static string _admin_editUser {
            get {
                return ResourceManager.GetString("_admin_editUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit password.
        /// </summary>
        public static string _admin_editUserPassword {
            get {
                return ResourceManager.GetString("_admin_editUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string _admin_product_TDESC {
            get {
                return ResourceManager.GetString("_admin_product_TDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string _admin_product_TDURATION {
            get {
                return ResourceManager.GetString("_admin_product_TDURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string _admin_product_TNAME {
            get {
                return ResourceManager.GetString("_admin_product_TNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture.
        /// </summary>
        public static string _admin_product_TPIC {
            get {
                return ResourceManager.GetString("_admin_product_TPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string _admin_product_TSTATE {
            get {
                return ResourceManager.GetString("_admin_product_TSTATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string _admin_product_TSTDATE {
            get {
                return ResourceManager.GetString("_admin_product_TSTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Price.
        /// </summary>
        public static string _admin_product_TSTPRICE {
            get {
                return ResourceManager.GetString("_admin_product_TSTPRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string _admin_remove {
            get {
                return ResourceManager.GetString("_admin_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove auction.
        /// </summary>
        public static string _admin_removeAuction {
            get {
                return ResourceManager.GetString("_admin_removeAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this object?.
        /// </summary>
        public static string _admin_removeAuction_Text {
            get {
                return ResourceManager.GetString("_admin_removeAuction_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove category.
        /// </summary>
        public static string _admin_removeCategory {
            get {
                return ResourceManager.GetString("_admin_removeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this object?.
        /// </summary>
        public static string _admin_removeCategory_Text {
            get {
                return ResourceManager.GetString("_admin_removeCategory_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove product.
        /// </summary>
        public static string _admin_removeProduct {
            get {
                return ResourceManager.GetString("_admin_removeProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this object?.
        /// </summary>
        public static string _admin_removeProduct_Text {
            get {
                return ResourceManager.GetString("_admin_removeProduct_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove user.
        /// </summary>
        public static string _admin_removeUser {
            get {
                return ResourceManager.GetString("_admin_removeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this object?.
        /// </summary>
        public static string _admin_removeUser_Text {
            get {
                return ResourceManager.GetString("_admin_removeUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string _admin_save {
            get {
                return ResourceManager.GetString("_admin_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        public static string _admin_user_NEWPASSWORD {
            get {
                return ResourceManager.GetString("_admin_user_NEWPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old password.
        /// </summary>
        public static string _admin_user_OLDPASSWORD {
            get {
                return ResourceManager.GetString("_admin_user_OLDPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat password.
        /// </summary>
        public static string _admin_user_REPEATPASSWORD {
            get {
                return ResourceManager.GetString("_admin_user_REPEATPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date registration.
        /// </summary>
        public static string _admin_user_TDATEREG {
            get {
                return ResourceManager.GetString("_admin_user_TDATEREG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat password.
        /// </summary>
        public static string _admin_user_TDPASSWORD {
            get {
                return ResourceManager.GetString("_admin_user_TDPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name.
        /// </summary>
        public static string _admin_user_TFNAME {
            get {
                return ResourceManager.GetString("_admin_user_TFNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locale.
        /// </summary>
        public static string _admin_user_TLOCALE {
            get {
                return ResourceManager.GetString("_admin_user_TLOCALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string _admin_user_TLOGIN {
            get {
                return ResourceManager.GetString("_admin_user_TLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        public static string _admin_user_TPASSWORD {
            get {
                return ResourceManager.GetString("_admin_user_TPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picture.
        /// </summary>
        public static string _admin_user_TPIC {
            get {
                return ResourceManager.GetString("_admin_user_TPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register date.
        /// </summary>
        public static string _admin_user_TRDATE {
            get {
                return ResourceManager.GetString("_admin_user_TRDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second name.
        /// </summary>
        public static string _admin_user_TSNAME {
            get {
                return ResourceManager.GetString("_admin_user_TSNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time zone.
        /// </summary>
        public static string _admin_user_TTZ {
            get {
                return ResourceManager.GetString("_admin_user_TTZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name of role.
        /// </summary>
        public static string _admin_userRole_TNAME {
            get {
                return ResourceManager.GetString("_admin_userRole_TNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to admin panel.
        /// </summary>
        public static string _admin_welcome {
            get {
                return ResourceManager.GetString("_admin_welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction.
        /// </summary>
        public static string _app {
            get {
                return ResourceManager.GetString("_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string _app_about {
            get {
                return ResourceManager.GetString("_app_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin panel.
        /// </summary>
        public static string _app_adminPanel {
            get {
                return ResourceManager.GetString("_app_adminPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged into the admin panel.
        /// </summary>
        public static string _app_adminPanel_Text {
            get {
                return ResourceManager.GetString("_app_adminPanel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auctions.
        /// </summary>
        public static string _app_auction {
            get {
                return ResourceManager.GetString("_app_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auctions.
        /// </summary>
        public static string _app_auctionHouse {
            get {
                return ResourceManager.GetString("_app_auctionHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string _app_category {
            get {
                return ResourceManager.GetString("_app_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string _app_contact {
            get {
                return ResourceManager.GetString("_app_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but all items to end.
        /// </summary>
        public static string _app_EmptyProducts {
            get {
                return ResourceManager.GetString("_app_EmptyProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string _app_Login {
            get {
                return ResourceManager.GetString("_app_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string _app_logOut {
            get {
                return ResourceManager.GetString("_app_logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string _app_moderate {
            get {
                return ResourceManager.GetString("_app_moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string _app_SignIn {
            get {
                return ResourceManager.GetString("_app_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spa.
        /// </summary>
        public static string _app_spa {
            get {
                return ResourceManager.GetString("_app_spa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go.
        /// </summary>
        public static string _app_TLetsGo {
            get {
                return ResourceManager.GetString("_app_TLetsGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string _app_TLogin {
            get {
                return ResourceManager.GetString("_app_TLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string _app_TPassword {
            get {
                return ResourceManager.GetString("_app_TPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        public static string _chooseLang {
            get {
                return ResourceManager.GetString("_chooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elmah monitor.
        /// </summary>
        public static string _elmah_monitor {
            get {
                return ResourceManager.GetString("_elmah_monitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page time out, may be delete or not exist.
        /// </summary>
        public static string _error404 {
            get {
                return ResourceManager.GetString("_error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string _home_createAccount {
            get {
                return ResourceManager.GetString("_home_createAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not filled.
        /// </summary>
        public static string _isNotFilled {
            get {
                return ResourceManager.GetString("_isNotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string _login {
            get {
                return ResourceManager.GetString("_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on main page.
        /// </summary>
        public static string _mainPage {
            get {
                return ResourceManager.GetString("_mainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string _menu_about {
            get {
                return ResourceManager.GetString("_menu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string _menu_admin {
            get {
                return ResourceManager.GetString("_menu_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction.
        /// </summary>
        public static string _menu_auction {
            get {
                return ResourceManager.GetString("_menu_auction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string _menu_category {
            get {
                return ResourceManager.GetString("_menu_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string _menu_contact {
            get {
                return ResourceManager.GetString("_menu_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string _menu_product {
            get {
                return ResourceManager.GetString("_menu_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string _menu_user {
            get {
                return ResourceManager.GetString("_menu_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized.
        /// </summary>
        public static string _notAuthorized {
            get {
                return ResourceManager.GetString("_notAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to see this page.
        /// </summary>
        public static string _notAuthorized_Text {
            get {
                return ResourceManager.GetString("_notAuthorized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not found.
        /// </summary>
        public static string _notFound {
            get {
                return ResourceManager.GetString("_notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing Moderate.
        /// </summary>
        public static string _NothingModerate {
            get {
                return ResourceManager.GetString("_NothingModerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page on url.
        /// </summary>
        public static string _pageNotFound {
            get {
                return ResourceManager.GetString("_pageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string _profile_changePassword {
            get {
                return ResourceManager.GetString("_profile_changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check product list.
        /// </summary>
        public static string _profile_checkProduct {
            get {
                return ResourceManager.GetString("_profile_checkProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check winning list.
        /// </summary>
        public static string _profile_checkWinnerList {
            get {
                return ResourceManager.GetString("_profile_checkWinnerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create product.
        /// </summary>
        public static string _profile_createProduct {
            get {
                return ResourceManager.GetString("_profile_createProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string _profile_edit {
            get {
                return ResourceManager.GetString("_profile_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can to change data and create model. Try it..
        /// </summary>
        public static string _profile_TDESCRIPTION {
            get {
                return ResourceManager.GetString("_profile_TDESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to profile.
        /// </summary>
        public static string _profile_TWELCOME {
            get {
                return ResourceManager.GetString("_profile_TWELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        public static string _role_admin {
            get {
                return ResourceManager.GetString("_role_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderator.
        /// </summary>
        public static string _role_moderator {
            get {
                return ResourceManager.GetString("_role_moderator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user.
        /// </summary>
        public static string _role_user {
            get {
                return ResourceManager.GetString("_role_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string _signIn {
            get {
                return ResourceManager.GetString("_signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to banned.
        /// </summary>
        public static string _state_banned {
            get {
                return ResourceManager.GetString("_state_banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draft.
        /// </summary>
        public static string _state_draft {
            get {
                return ResourceManager.GetString("_state_draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outdated.
        /// </summary>
        public static string _state_outdated {
            get {
                return ResourceManager.GetString("_state_outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selling.
        /// </summary>
        public static string _state_selling {
            get {
                return ResourceManager.GetString("_state_selling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auction not found.
        /// </summary>
        public static string errAuctionNotFound {
            get {
                return ResourceManager.GetString("errAuctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fields not compare.
        /// </summary>
        public static string errCompare {
            get {
                return ResourceManager.GetString("errCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to try again.
        /// </summary>
        public static string errCreate {
            get {
                return ResourceManager.GetString("errCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datetime not correct.
        /// </summary>
        public static string errDateTime {
            get {
                return ResourceManager.GetString("errDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to columns of password not equal .
        /// </summary>
        public static string errDPassword {
            get {
                return ResourceManager.GetString("errDPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration not correct.
        /// </summary>
        public static string errDuration {
            get {
                return ResourceManager.GetString("errDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locale not found.
        /// </summary>
        public static string errLocaleNotFound {
            get {
                return ResourceManager.GetString("errLocaleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not unique.
        /// </summary>
        public static string errNotUnique {
            get {
                return ResourceManager.GetString("errNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can not update this item.
        /// </summary>
        public static string errNotUpdate {
            get {
                return ResourceManager.GetString("errNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password not compare.
        /// </summary>
        public static string errOldPassword {
            get {
                return ResourceManager.GetString("errOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only symbols .
        /// </summary>
        public static string errOnlySymbol {
            get {
                return ResourceManager.GetString("errOnlySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and new passwords compared.
        /// </summary>
        public static string errPasswordCompare {
            get {
                return ResourceManager.GetString("errPasswordCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file not found.
        /// </summary>
        public static string errPicture {
            get {
                return ResourceManager.GetString("errPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not correct format file.
        /// </summary>
        public static string errPictureFormat {
            get {
                return ResourceManager.GetString("errPictureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not correct price.
        /// </summary>
        public static string errPrice {
            get {
                return ResourceManager.GetString("errPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not correct range.
        /// </summary>
        public static string errRange {
            get {
                return ResourceManager.GetString("errRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this field is required.
        /// </summary>
        public static string errRequired {
            get {
                return ResourceManager.GetString("errRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to length not correct.
        /// </summary>
        public static string errStringLength {
            get {
                return ResourceManager.GetString("errStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timezone not found.
        /// </summary>
        public static string errTimeZoneNotFound {
            get {
                return ResourceManager.GetString("errTimeZoneNotFound", resourceCulture);
            }
        }
    }
}
